bundler_args: --without development
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - rbx-2
  - jruby-19mode
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
sudo: false
